extension FilmPreset {
    func copy(
        name: String? = nil,
        author: String? = nil,
        negativeExposure: Float? = nil,
        developmentGamma: Float? = nil,
        printContrast: Float? = nil,
        dyeDensity: Float? = nil,
        colorCrosstalk: Float? = nil,
        highlightRolloff: Float? = nil,
        shadowLift: Float? = nil,
        printWarmth: Float? = nil,
        layerSpeeds: SIMD3<Float>? = nil,
        layerCrossovers: SIMD3<Float>? = nil,
        adjacencyStrength: Float? = nil,
        grainRoughness: Float? = nil,
        halationSpreadScale: Float? = nil,
        halationThresholdOffset: Float? = nil,
        cineToneIntensity: Float? = nil,
        grainIntensity: Float? = nil,
        halationIntensity: Float? = nil,
        halationTintCore: SIMD3<Float>? = nil,
        halationTintMid: SIMD3<Float>? = nil,
        halationTintEdge: SIMD3<Float>? = nil,
        halationStrength: Float? = nil,
        channelMixerRed: SIMD3<Float>? = nil,
        channelMixerGreen: SIMD3<Float>? = nil,
        channelMixerBlue: SIMD3<Float>? = nil
    ) -> FilmPreset {
        FilmPreset(
            name: name ?? self.name,
            author: author ?? self.author,
            negativeExposure: negativeExposure ?? self.negativeExposure,
            developmentGamma: developmentGamma ?? self.developmentGamma,
            printContrast: printContrast ?? self.printContrast,
            dyeDensity: dyeDensity ?? self.dyeDensity,
            colorCrosstalk: colorCrosstalk ?? self.colorCrosstalk,
            highlightRolloff: highlightRolloff ?? self.highlightRolloff,
            shadowLift: shadowLift ?? self.shadowLift,
            printWarmth: printWarmth ?? self.printWarmth,
            layerSpeeds: layerSpeeds ?? self.layerSpeeds,
            layerCrossovers: layerCrossovers ?? self.layerCrossovers,
            adjacencyStrength: adjacencyStrength ?? self.adjacencyStrength,
            grainRoughness: grainRoughness ?? self.grainRoughness,
            halationSpreadScale: halationSpreadScale ?? self.halationSpreadScale,
            halationThresholdOffset: halationThresholdOffset ?? self.halationThresholdOffset,
            cineToneIntensity: cineToneIntensity ?? self.cineToneIntensity,
            grainIntensity: grainIntensity ?? self.grainIntensity,
            halationIntensity: halationIntensity ?? self.halationIntensity,
            halationTintCore: halationTintCore ?? self.halationTintCore,
            halationTintMid: halationTintMid ?? self.halationTintMid,
            halationTintEdge: halationTintEdge ?? self.halationTintEdge,
            halationStrength: halationStrength ?? self.halationStrength,
            channelMixerRed: channelMixerRed ?? self.channelMixerRed,
            channelMixerGreen: channelMixerGreen ?? self.channelMixerGreen,
            channelMixerBlue: channelMixerBlue ?? self.channelMixerBlue
        )
    }
}
