import re
import os

# Configuration
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STRINGS_PATH = os.path.join(PROJECT_ROOT, "Yoyo/en.lproj/Localizable.strings")
OUTPUT_PATH = os.path.join(PROJECT_ROOT, "Yoyo/Generated/String+Localized.swift")

HEADER = """// This file is auto-generated by scripts/generate_localized_strings.py
// DO NOT EDIT MANUALLY

import Foundation

extension String {
    /// Get the localized string
    var localized: String {
        NSLocalizedString(self, tableName: nil, bundle: LanguageManager.shared.bundle, value: "", comment: "")
    }

    /// Get the localized string with arguments
    func localized(_ arguments: CVarArg...) -> String {
        String(format: NSLocalizedString(self, tableName: nil, bundle: LanguageManager.shared.bundle, value: "", comment: ""), arguments: arguments)
    }

    /// Get the localized string with a comment
    func localized(comment: String) -> String {
        NSLocalizedString(self, tableName: nil, bundle: LanguageManager.shared.bundle, value: "", comment: comment)
    }
"""

FOOTER = """}
"""

def to_camel_case(snake_str):
    components = snake_str.split('_')
    # We capitalize the first letter of each component except the first one
    # with the 'title' method and join them together.
    return components[0] + ''.join(x.title() for x in components[1:])

def generate():
    if not os.path.exists(STRINGS_PATH):
        print(f"Error: {STRINGS_PATH} not found")
        return

    print(f"Reading {STRINGS_PATH}...")
    
    generated_lines = []
    
    with open(STRINGS_PATH, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    # Regex to match "key" = "value";
    # We allow spaces around = and ;
    key_pattern = re.compile(r'"([^"]+)"\s*=\s*"((?:[^"\\]|\\.)*)"\s*;')
    
    # Track keys to prevent duplicates
    seen_keys = set()

    for line in lines:
        stripped = line.strip()
        
        # Preserve empty lines
        if not stripped:
            generated_lines.append("")
            continue
            
        # Preserve comments
        if stripped.startswith("//"):
            generated_lines.append(f"    {stripped}")
            continue

        # Parse key-value
        match = key_pattern.search(line)
        if match:
            key = match.group(1)
            # value = match.group(2) # We don't need value for the static let
            
            if key in seen_keys:
                continue
            seen_keys.add(key)
            
            var_name = to_camel_case(key)
            
            # Swift keywords check (basic)
            if var_name in ["default", "case", "for", "in", "let", "var", "func", "return", "switch", "if", "else", "continue", "break"]:
                var_name = f"`{var_name}`"

            generated_lines.append(f"    static let {var_name} = \"{key}\"")

    print(f"Generating {OUTPUT_PATH}...")
    
    with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
        f.write(HEADER)
        f.write('\n'.join(generated_lines))
        f.write('\n')
        f.write(FOOTER)

    print("Done! Generated/String+Localized.swift has been updated.")

if __name__ == "__main__":
    generate()
